# Generated by Django 4.1.3 on 2023-01-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фотография')),
                ('work_experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('employer', models.TextField(blank=True, verbose_name='Работодатель')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancy.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'вакансию',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
